### ISSUE TITLE
Random generation of enums never includes the last enum-value

### ISSUE THREAD

**Issue by PureKrome** [nbuilder/nbuilder#79]
So if I wish to generate a random enum using this code ...

```
var statusType = GetRandom.Enumeration<StatusType>();
```

the result will be random, but it will **NEVER include the last enum value**. 

### Update

My initial reason was wrong, which was why I crossed out the convo below but didn't delete it for future reference, etc.

---

~why? [cause of this](https://twitter.com/purekrome/status/966511079672070144)..~

![image](https://user-images.githubusercontent.com/899878/36519248-7ef32c9a-17de-11e8-8a3d-70146f47b759.png)

~So basically, [with the .NET Random.Next(min, max) method](https://msdn.microsoft.com/en-us/library/2dx6wyd4(v=vs.110).aspx) :-~
~- `min` is INCLUSIVE (i.e. a _possible_ random result)~
~- `max` is EXCLUSIVE (i.e. will _never_ be a possible random result)~

![](https://media.giphy.com/media/wxw2e19ZMsjio/giphy.gif)

![](https://media.giphy.com/media/3oEjHKvjqt5pssL99C/giphy.gif)

~So to me this is crazy talk, but I cannot change the way `Random.Next` is implemented.~

----

~So this means, to fix this issue ... I'm not going to make any suggestions about all the non-enum methods, but for the enum one, I can just bump the `max` value.~

~PR incoming...~

**Comment by PureKrome** [comment]
Ok - so it seems like the code _looks_ ok, but it still errors. So, heres a repo which can reproduce the errors:

```
using FizzWare.NBuilder;
using FizzWare.NBuilder.Generators;
using System;
using Xunit;

namespace nbuild_tests
{
    public class UnitTest1
    {
        private readonly Random rnd = new Random(System.Guid.NewGuid().GetHashCode());

        [Fact]
        public void TestPasses()
        {
            int counter = 0;
         
            for(int i = 0; i < 100000; i++)
            {
                var values = EnumHelper.GetValues(typeof(StatusType));
                var index = Next(0, values.Length);
                var statusType = (StatusType)values.GetValue(index);

                if (statusType == StatusType.Pink_LastItemInEnumCollection)
                {
                    counter++;
                }
            }

            Assert.True(counter > 0);
        }

        [Fact]
        public void TestFails_ButShouldPass()
        {
            int counter = 0;
         
            for(int i = 0; i < 100000; i++)
            {
                var statusType = GetRandom.Enumeration<StatusType>();
                if (statusType == StatusType.Pink_LastItemInEnumCollection)
                {
                    counter++;
                }
            }

            Assert.True(counter > 0);
        }

        // internal "Next" commad for getting the next random number.
        public virtual int Next(int min, int max)
        {
            return rnd.Next(min, max);
        }

        // Test Enum.
        public enum StatusType
        {
            Unknown,
            Red,
            Green,
            Blue,
            Pink_LastItemInEnumCollection
        }
    }
}
```

**Comment by crmckenzie** [comment]
Fixed in develop.

**Comment by Doug-Murphy** [comment]
This is still an issue for the other `Enumeration(Type type)` method. PR incoming.
